name: SwiftShader - Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-pragma-server:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build SwiftShader
        shell: bash
        run: |
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Generate Release Archive
        shell: bash
        working-directory: ${{inputs.working-directory}}
        id: generate-archive
        run: |
          archiveName=swiftshader.zip
          vcpkg install 7zip
          cd build/bin/
          "7z.exe" a ../../$archiveName "vulkan-1.dll" -r
          echo "archive-name=$archiveName" >> $GITHUB_OUTPUT
          
      - name: Build Tag Name
        id: build_tag_name
        shell: bash
        run: |
          echo "tag_name=$(TZ='Europe/Berlin' date +%F)" >> $GITHUB_OUTPUT

      - name: Update Nightly Tag
        uses: rickstaa/action-create-tag@v1.3.9
        continue-on-error: true
        if: runner.os == 'Linux' && ${{ inputs.update_tag == '1' }}
        with:
          tag: '${{ steps.build_tag_name.outputs.tag_name }}'
          force_push_tag: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.generate-archive.outputs.archive-name }}"
          body: "Automatically generated binaries."
          tag: '${{ steps.build_tag_name.outputs.tag_name }}'
          replacesArtifacts: true
          allowUpdates: true
